# Page settings
baseurl = "localhost:1313"
title = "I.S.B Hockey Subacuático"
languageCode = "es-es"
defaultContentLanguage = "es"
theme = "hugo-elate-theme"

[languages]
  [languages.es]
    title = "I.S.B Hockey Subacuático"
    weight = 1

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Navigation
  [params.navigation]
    brand = "ISB"
    home = "Inicio"

  [[params.navigation.item]]
    title = "Juega con nosotros"
    anchor = "work"
    enable = true
  [[params.navigation.item]]
    title = "Horarios"
    anchor = "schedule"
    enable = true
  [[params.navigation.item]]
    title = "Estadísticas"
    anchor = "counters"
    enable = true
  [[params.navigation.item]]
    title = "Contacto"
    anchor = "contact"
    enable = true
  
  # Hero section
  [params.hero]
    title = "I.S.B Hockey Subacuático"
    subtitle = 'Club de Hockey Subacuático en Barcelona'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Hockey subacuático en acción"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=a9G-I6P3mYs"


  # Work section
  [params.work]
    enable = true
    title = "Juega con nosotros"
    description = "Ven a jugar con nosotros. ¡Te encantará!"
    footertext = 'TODO: Find a good image to show here'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Jugadores"
      icon = "icon-people"
      from = 0
      to = 999
      interval = 1
      speed = 5000

    [[params.counters.item]]
      description = "Horas en apnea al día"
      icon = "icon-spinner"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Campeonatos ganados"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "???"
      icon = "icon-code"
      from = 0
      to = 52
      interval = 50
      speed = 5000

# About section
   [params.schedule]
    enable = true
    title = "Horarios"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    times = ["09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00"]
    days = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]


    [[params.schedule.event]]
      name = "Entreno 1"
      description = "Media hora entrenamiento seco. Media hora natación. Una hora de partido"
      day = "Lunes"
      start = "20:00"
      end = "22:00"

    [[params.schedule.event]]
      name = "Entreno 2"
      description = "Media hora entrenamiento seco. Media hora natación. Una hora de partido"
      day = "Miércoles"
      start = "12:00"
      end = "14:00"


  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Contacto"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "CEM Besòs, Ronda de Sant Ramon de Penyafort 08930 Barcelona"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "hoqueisub@gmail.com"],
      ]

    name = "Nombre"
    email = "Email"
    message = "Mensaje"
    button = "Enviar mensaje"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
